### PR TITLE
Removing node_modules

### PR DESCRIPTION
**Pull request by tdmiller1**
Thought it might be nice to remove the node_modules and let the .gitignore take care of the rest

### CODE REVIEW

**Comment by manoonan1** [comment]
Much appreciated... Can never figure out how to get my dang .gitignore to work.

**Review by manoonan1 — APPROVED** [review]
thats a lot of lines, gee

**Comment by tdmiller1** [comment]
Yeah I was actually pretty confused cause I thought it was working like it's supposed to, I think it's something to do with committing node_modules _before_ the .gitignore, but anyways🥂  thanks for the repo Star btw

**Comment by manoonan1** [comment]
No problem! Did you actually get to try it? Also once I saw your readme I realized now I need to make one lol

**Comment by tdmiller1** [comment]
Nope I actually wasn't sure what type of Bot it was, how can I can test it out? I hopped into Davids stream yesterday and had him explain it to me a bit. Seems very cool, I just realized I had a couple public repos that I wasn't sure how they'd look haha glad ya liked my Readme

**Comment by manoonan1** [comment]
It should be set to test at any moment as it is hosted in heroku. But, for the sake of explaining too much on this random comment lol, I will start on that Readme and do a push.

**Pull request merged**
